image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
- pip install -r requirements/appveyor.txt

build_script:
- flet pack main.py --name incolume-py-sorteio --icon asserts/icon.png --product-name incolume-py-sorteio --product-version "1.2.3" --copyright "Copyright (c) since 2010 Incolume."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
#
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a incolume-py-sorteio-win.zip %CD%\dist\*.exe

  artifacts:
  - path: incolume-py-sorteio-win.zip

#
#   macOS package
#
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf incolume-py-sorteio-macos.tar.gz -C dist incolume-py-sorteio.app

  artifacts:
  - path: incolume-py-sorteio-macos.tar.gz

#
#   Linux package
#
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf incolume-py-sorteio-lin.tar.gz -C dist incolume-py-sorteio

  artifacts:
  - path: incolume-py-sorteio-lin.tar.gz
